services:
  ircd_linked:
    build:
        context: .
        args:
            BUILD_SERVER_NAME: ${SERVER_NAME}
    image: inspi4
    network_mode: "host"
    env_file: "config.env"
    volumes:
        - ./include.conf:/etc/inspircd/include.conf:ro
        - ssl:/etc/ssl/inspircd
        - data:/var/lib/inspircd
        - log:/var/log/inspircd
volumes:
    data:
        name: inspi4_data
    ssl:
        name: inspi4_ssl
    log:
        name: inspi4_log
